#!/bin/bash

DOWNLOADS=$HOME/Downloads

# Lists the last downloaded file
ldown() { 
  echo $DOWNLOADS/$(ls -t $DOWNLOADS | head -1)
}

# Moves the last downloaded file
mdown() {
  mv "`ldown`" $1
}

# Copies the last downloaded file
cdown() {
  cp "`ldown`" $1
}

# Sets and changes to the work directory
cw() {
  if [ $# -gt 0 ]; then
    set_cw $1
  fi

  if [ "$CW" == "" ]; then
    load_cw
  fi 

  cd $CW
}

# Loads the current working directory from the configuration file
load_cw() {
  source ~/.cw
}

# Sets the current working directory
set_cw() {
    CW="$(PWD)/$1"
    echo "export CW=$CW" > ~/.cw
    echo "Current working directory set to $CW"
}

# Prints out the current working directory
cw?() {
  load_cw
  echo "$CW"
}
