#!/bin/bash

DOWNLOADS=$HOME/Downloads

# Lists the last downloaded file
ldown() { 
  echo $DOWNLOADS/$(ls -t $DOWNLOADS | head -1)
}

# Moves the last downloaded file
mdown() {
  mv "`ldown`" $1
}

# Copies the last downloaded file
cdown() {
  cp "`ldown`" $1
}

# Resolves the ecom dependencies
resolve_ecom() {
    gg;
    cd build/buildeng;
    sed 's/<env key="VERSIONER_PERL_VERSION" value="5.8.9"\/>//' <dependency.xml > dependency-tmp.xml; 
    mv dependency-tmp.xml dependency.xml;
    gb;
    rake solr;
    rake components;
    rake ecom;
    gg;
    cd build/buildeng;
    git checkout dependency.xml;
} 

# Sets and changes to the work directory
cw() {
  if [ $# -gt 0 ]; then
    set_cw $1
  fi

  if [ "$CW" == "" ]; then
    load_cw
  fi 

  cd $CW
}

# Loads the current working directory from the configuration file
load_cw() {
  source ~/.cw
}

# Sets the current working directory
set_cw() {
    CW="$(PWD)/$1"
    echo "export CW=$CW" > ~/.cw
    echo "Current working directory set to $CW"
}

# Prints out the current working directory
cw?() {
  load_cw
  echo "$CW"
}
