source "$HOME/.dots/bash/conf/path"
source "$HOME/.dots/bash/conf/aliases"
source "$HOME/.dots/bash/conf/functions"
source "$HOME/.dots/bash/conf/general"
source "$HOME/.dots/bash/conf/bash_completion"
source "$HOME/.dots/bash/conf/rbenv"

#source bash_profile.local if it exists
if [ -e "$HOME/.bash_profile.local" ]; then
  source "$HOME/.bash_profile.local"
fi
